export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>头部不会重新渲染</header>
        <main>{children}</main>
        <footer>底部不会重新渲染</footer>
      </body>
    </html>
  );
}
